### ISSUE TITLE
Permission denied Quanty executable

### ISSUE THREAD

**Issue by mretegan** [mretegan/crispy#49]
If the Quanty binary is not executable.

```python
Traceback (most recent call last):
  File "/home/marius/crispy-0.7.3/lib/python3.8/site-packages/crispy/gui/quanty.py", line 1587, in runCalculation
    subprocess.call(command, stdout=f, stderr=f)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/marius/Downloads/Quanty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marius/crispy-0.7.3/lib/python3.8/site-packages/crispy/gui/quanty.py", line 1589, in runCalculation
    if e.errno == os.errno.ENOENT:
AttributeError: module 'os' has no attribute 'errno'
Aborted (core dumped)
```

**Comment by mretegan** [comment]
Fixed in https://github.com/mretegan/crispy/commit/e112d89b8d7e4c32622178de518b08c9a60f9b55.
