### ISSUE TITLE
Invalid path in the config file

### ISSUE THREAD

**Issue by mretegan** [mretegan/crispy#69]
Running calculations fails if the current folder path gets corrupted. 

```
Traceback (most recent call last):
  File "/Users/marius/crispy/crispy/quanty/main.py", line 501, in run
    self.state.run()
  File "/Users/marius/crispy/crispy/quanty/calculation.py", line 743, in run
    self.saveInput()
  File "/Users/marius/crispy/crispy/quanty/calculation.py", line 736, in saveInput
    os.chdir(settings.value("CurrentPath"))
TypeError: chdir: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by mretegan** [comment]
Fixed in https://github.com/mretegan/crispy/commit/71627e062a5ba4fc8fba6428edf6fc90f3cdd4b8
