### ISSUE TITLE
PyPI package outdated, broken

### ISSUE THREAD

**Issue by mueslo** [mretegan/crispy#79]
`setup.py` fails because due to some circularity it imports code it needs to install first.

```console
(venv) user@host:~$ pip install crispy
Collecting crispy
  Using cached crispy-0.7.3.tar.gz (409 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-prllqu5t/crispy_0d13376086e942c086aa74f8ba8a6c16/setup.py", line 149, in <module>
          main()
        File "/tmp/pip-install-prllqu5t/crispy_0d13376086e942c086aa74f8ba8a6c16/setup.py", line 77, in main
          version=get_version(),
        File "/tmp/pip-install-prllqu5t/crispy_0d13376086e942c086aa74f8ba8a6c16/setup.py", line 53, in get_version
          from crispy import version
        File "/tmp/pip-install-prllqu5t/crispy_0d13376086e942c086aa74f8ba8a6c16/crispy/__init__.py", line 3, in <module>
          from silx.resources import register_resource_directory
      ModuleNotFoundError: No module named 'silx'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Directly installing from github main branch (`pip install git+https://github.com/mretegan/crispy.git`) works, so the solution would be to push out a new stable version finally or patch 0.7.3)

**Comment by mretegan** [comment]
Thanks for reporting the issue, and sorry it took ages to solve. The new version fixes the PyPI installation issues.
