### ISSUE TITLE
Error on launching Crispy

### ISSUE THREAD

**Issue by yohey-uemura** [mretegan/crispy#81]
Hi all,

I installed the latest version of Crispy on my laptop (macOS, M1, sonoma 14.5) https://www.esrf.fr/computing/scientific/crispy/downloads.html

However, I could not launch Crispy.

I installed using "pip" and I got the following error.
```
Traceback (most recent call last):
  File "/Users/uemuray/Apps/crispy/bin/./crispy", line 24, in <module>
    main()
  File "/Users/uemuray/Apps/crispy/bin/./crispy", line 20, in main
    main()
  File "/Users/uemuray/Apps/crispy/crispy/__main__.py", line 51, in main
    window = MainWindow()
  File "/Users/uemuray/Apps/crispy/crispy/gui/main.py", line 73, in __init__
    self.aboutDialog = AboutDialog(parent=self)
  File "/Users/uemuray/Apps/crispy/crispy/gui/main.py", line 245, in __init__
    self.updateCheckBox.setChecked(int(updateCheck))
ValueError: invalid literal for int() with base 10: 'true'
```

I modified "gui.py" according to the error as follows:

```
if type(updateCheck) is str:
     if updateCheck == 'true' or updateCheck == 'True':
          updateCheck = True
     else:
           updateCheck = False
```

I did not investigate what caused this error. 
I hope that this report helps to fix the error.

Best regards,
Yohei

**Comment by mretegan** [comment]
Fixed in version 0.8.0.
